### ISSUE TITLE
koa-cola dev 跑不起来，在window10下

### ISSUE THREAD

**Issue by w567675** [hcnode/koa-cola#9]
```js
koa-cola dev
```

![image](https://user-images.githubusercontent.com/6658087/40103116-f8d9286c-591e-11e8-9671-bd0b9be742b4.png)

改成 
package.json
```js  
"scripts": {
    "dev": "node node_modules/koa-cola/bin/koa-cola dev"
  },
```
npm run dev  没问题

**Comment by hcnode** [comment]
嗯，看上去这个错误是没找到global的webpack命令

**Comment by hcnode** [comment]
0.6.1去掉全局的webpack和ts-node依赖
